In [1]:
print("Jupyter is working inside VS Code")

Jupyter is working inside VS Code

In [2]:
print("Jupyter is now working perfectly")

Jupyter is now working perfectly

In [3]:
import pandas as pd

In [13]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'analysis.ipynb', 'hotel_bookings.csv', 'python-projects', 'sharedStorage', 'Untitled.ipynb']

In [14]:
import pandas as pd

df = pd.read_csv('hotel_bookings.csv')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01-07-15
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01-07-15
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,02-07-15
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,02-07-15
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,03-07-15

In [15]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [16]:
df.shape

(119390, 32)

In [17]:
import pandas as pd

df = pd.read_csv('hotel_bookings.csv')
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01-07-15
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01-07-15
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,02-07-15
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,02-07-15
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,03-07-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06-09-17
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07-09-17
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07-09-17
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07-09-17
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07-09-17

In [1]:
import pandas as pd

df = pd.read_csv('employee_records.csv')
df

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Bonus,Tax Rate %,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,"142,278.32","10,000",0.15,06/04/2023
1,2,Ethan Brown,44,India,Marketing,Executive,"98,549.20","5,000",0.15,1/13/2018
2,3,Sophia Martinez,51,Japan,Finance,Developer,"85,565.84","5,000",0.10,4/30/2015
3,4,Ethan Martinez,47,Germany,Support,Analyst,"34,513.67","2,000",0.10,6/17/2015
4,5,Mia Brown,32,Australia,Support,Consultant,"45,339.72","2,000",0.05,2/22/2019
...,...,...,...,...,...,...,...,...,...,...
29995,29996,Mia Brown,42,Australia,Support,Manager,"133,474.82","10,000",0.15,07/03/2015
29996,29997,Mason Thomas,41,Mexico,Engineering,Assistant,"140,793.59","10,000",0.15,10/12/2023
29997,29998,Lily Anderson,44,India,Marketing,Developer,"68,464.72","5,000",0.15,6/28/2021
29998,29999,Mason Taylor,46,Brazil,Finance,Assistant,"148,323.28","10,000",0.10,11/11/2017
29999,30000,Lucas Jackson,30,Mexico,Finance,Developer,"93,451.72","5,000",0.15,3/17/2017

In [2]:
import pandas as pd

df = pd.read_csv('employee_records.csv')
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Bonus,Tax Rate %,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,"142,278.32","10,000",0.15,06/04/2023
1,2,Ethan Brown,44,India,Marketing,Executive,"98,549.20","5,000",0.15,1/13/2018
2,3,Sophia Martinez,51,Japan,Finance,Developer,"85,565.84","5,000",0.10,4/30/2015
3,4,Ethan Martinez,47,Germany,Support,Analyst,"34,513.67","2,000",0.10,6/17/2015
4,5,Mia Brown,32,Australia,Support,Consultant,"45,339.72","2,000",0.05,2/22/2019

In [3]:
df.shape

(30000, 10)

In [4]:
df.info()
df.describe

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  str
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  str
 4   Department     30000 non-null  str
 5   Position       30000 non-null  str
 6   Salary         30000 non-null  str
 7   Bonus          30000 non-null  str
 8   Tax Rate %     30000 non-null  float64
 9   Joining_Date   30000 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 2.3 MB

<bound method NDFrame.describe of        Employee_ID    Employee_Name  Age    Country   Department    Position  \
0                1    Daniel Taylor   25         UK           HR     Analyst
1                2      Ethan Brown   44      India    Marketing   Executive
2                3  Sophia Martinez   51      Japan      Finance   Developer
3                4   Ethan Martinez   47    Germany      Support     Analyst
4                5        Mia Brown   32  Australia      Support  Consultant
...            ...              ...  ...        ...          ...         ...
29995        29996        Mia Brown   42  Australia      Support     Manager
29996        29997     Mason Thomas   41     Mexico  Engineering   Assistant
29997        29998    Lily Anderson   44      India    Marketing   Developer
29998        29999     Mason Taylor   46     Brazil      Finance   Assistant
29999        30000    Lucas Jackson   30     Mexico      Finance   Developer

           Salary   Bonus  Tax Rate % Joining_Date
0      142,278.32  10,000        0.15   06/04/2023
1       98,549.20   5,000        0.15    1/13/2018
2       85,565.84   5,000        0.10    4/30/2015
3       34,513.67   2,000        0.10    6/17/2015
4       45,339.72   2,000        0.05    2/22/2019
...           ...     ...         ...          ...
29995  133,474.82  10,000        0.15   07/03/2015
29996  140,793.59  10,000        0.15   10/12/2023
29997   68,464.72   5,000        0.15    6/28/2021
29998  148,323.28  10,000        0.10   11/11/2017
29999   93,451.72   5,000        0.15    3/17/2017

[30000 rows x 10 columns]>

In [5]:
print(df["Salary"].dtype)

str

In [6]:
df["Bonus"]= df["Bonus"].str.replace(",", "")
df["Bonus"]= df["Bonus"].astype(float)

df["Salary"] = df["Salary"].str.replace(",", "")
df["Salary"] = df["Salary"].astype(float)

In [7]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  str
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  str
 4   Department     30000 non-null  str
 5   Position       30000 non-null  str
 6   Salary         30000 non-null  float64
 7   Bonus          30000 non-null  float64
 8   Tax Rate %     30000 non-null  float64
 9   Joining_Date   30000 non-null  str
dtypes: float64(3), int64(2), str(5)
memory usage: 2.3 MB
None

In [9]:
print(df["Joining_Date"].head(30))

0     06/04/2023
1      1/13/2018
2      4/30/2015
3      6/17/2015
4      2/22/2019
5      9/29/2018
6      8/24/2021
7     01/08/2021
8     12/20/2018
9      5/18/2018
10     8/22/2024
11    11/20/2016
12    07/03/2024
13    11/12/2017
14    09/07/2021
15    10/11/2021
16    08/10/2016
17     2/20/2017
18    12/04/2021
19    03/01/2021
20     8/24/2022
21    10/25/2021
22    11/09/2018
23     4/16/2022
24    01/09/2021
25     4/25/2015
26    05/12/2024
27     7/21/2024
28    11/04/2016
29    08/03/2022
Name: Joining_Date, dtype: str

In [ ]:
df["Joining_Date"] =pd.to_datetime(df["Joining_Date"])

In [11]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  str
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  str
 4   Department     30000 non-null  str
 5   Position       30000 non-null  str
 6   Salary         30000 non-null  float64
 7   Bonus          30000 non-null  float64
 8   Tax Rate %     30000 non-null  float64
 9   Joining_Date   30000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 2.3 MB
None

In [3]:
import pandas as pd
df = pd.read_csv("employee_records.csv")

In [4]:
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Bonus,Tax Rate %,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,"142,278.32","10,000",0.15,06/04/2023
1,2,Ethan Brown,44,India,Marketing,Executive,"98,549.20","5,000",0.15,1/13/2018
2,3,Sophia Martinez,51,Japan,Finance,Developer,"85,565.84","5,000",0.10,4/30/2015
3,4,Ethan Martinez,47,Germany,Support,Analyst,"34,513.67","2,000",0.10,6/17/2015
4,5,Mia Brown,32,Australia,Support,Consultant,"45,339.72","2,000",0.05,2/22/2019

In [5]:
df.isnull().sum()

Employee_ID      0
Employee_Name    0
Age              0
Country          0
Department       0
Position         0
Salary           0
Bonus            0
Tax Rate %       0
Joining_Date     0
dtype: int64

In [6]:
df["Department"].value_counts()

Department
Engineering    5070
Sales          5019
Marketing      5007
Support        4990
HR             4976
Finance        4938
Name: count, dtype: int64

In [7]:
df["Position"].value_counts()

Position
Executive     5124
Consultant    5022
Analyst       5008
Developer     4988
Assistant     4934
Manager       4924
Name: count, dtype: int64

In [8]:
df["Country"].value_counts()

Country
Germany      3090
Australia    3052
UK           3021
France       3010
Mexico       2991
India        2985
Canada       2969
USA          2967
Brazil       2961
Japan        2954
Name: count, dtype: int64

In [9]:
df.describe()

        Employee_ID           Age    Tax Rate %
count  30000.000000  30000.000000  30000.000000
mean   15000.500000     40.978067      0.112292
std     8660.398374     11.234432      0.036038
min        1.000000     22.000000      0.050000
25%     7500.750000     31.000000      0.100000
50%    15000.500000     41.000000      0.100000
75%    22500.250000     51.000000      0.150000
max    30000.000000     60.000000      0.150000

In [13]:
pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.2-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\PC\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.51-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 1.1 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 1.1 MB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.1 MB 1.2 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 1.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.2 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 1.2 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.0 MB/s  0:00:02
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.2-cp314-cp314-win_amd64.whl (240 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [pymysql]
   ---------------------------------------- 0/3 [pymysql]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.2 pymysql-1.2.0 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
from sqlalchemy import create_engine

In [17]:
import pymysql

In [20]:
from sqlalchemy import create_engine
engine = create_engine(
"mysql+pymysql://root:Mtakaison96#@localhost/hr_analytics")
print("Connection ready")

Connection ready

In [21]:
engine.connect()
print("MySQL connection successful")

MySQL connection successful

In [22]:
df.to_sql(
    name= "employee_records",
    con=engine,
    if_exists="replace",
    index=False
)
print("upload complete")

upload complete

In [2]:
import pandas as pd
df = pd.read_csv("employee_records.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  str
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  str
 4   Department     30000 non-null  str
 5   Position       30000 non-null  str
 6   Salary         30000 non-null  str
 7   Bonus          30000 non-null  str
 8   Tax Rate %     30000 non-null  float64
 9   Joining_Date   30000 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 2.3 MB

In [4]:
df.shape

(30000, 10)

In [5]:
df["Bonus"]= df["Bonus"].str.replace(",", "")
df["Bonus"]= df["Bonus"].astype(float)

df["Salary"] = df["Salary"].str.replace(",", "")
df["Salary"] = df["Salary"].astype(float)

df["Joining_Date"] =pd.to_datetime(df["Joining_Date"])

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  str
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  str
 4   Department     30000 non-null  str
 5   Position       30000 non-null  str
 6   Salary         30000 non-null  float64
 7   Bonus          30000 non-null  float64
 8   Tax Rate %     30000 non-null  float64
 9   Joining_Date   30000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 2.3 MB

In [9]:
from sqlalchemy import create_engine
engine = create_engine(
"mysql+pymysql://root:Mtakaison96#@localhost/hr_analytics")

In [10]:
engine.connect()
print("MySQL connection successful")

MySQL connection successful

In [11]:
df.to_sql(
    name= "employee_records",
    con=engine,
    if_exists="replace",
    index=False
)
print("upload complete")

upload complete

In [12]:
df[["Salary", "Bonus"]].dtypes

Salary    float64
Bonus     float64
dtype: object